uav1:
  type: scout
  capabilities: fire_visual, fire_thermal, human_visual, human_audio
  human_visual_prob:
    local: 0.8
    neighbour: 0.0

  human_audio_prob:
    local: 0.8
    neighbour: 0.2

  fire_visual_prob:
    local: 0.8
    neighbour: 0.0

  fire_thermal_prob:
    local: 0.8
    neighbour: 0.3

  failure_prob: 0.05

uav2:
  type: firefighter
  capabilities: fire_visual, fire_thermal
  fire_visual_prob:
    local: 0.8
    neighbour: 0.0

  fire_thermal_prob:
    local: 0.8
    neighbour: 0.3

  failure_prob: 0.05

uav3:
  type: scout
  capabilities: fire_visual, human_visual, human_audio
  human_visual_prob:
    local: 0.8
    neighbour: 0.0

  human_audio_prob:
    local: 0.8
    neighbour: 0.2

  fire_visual_prob:
    local: 0.8
    neighbour: 0.0

  failure_prob: 0.05


ugv1:
  type: scout
  capabilities: fire_visual, fire_thermal, human_visual, human_audio
  human_visual_prob:
    local: 0.8
    neighbour: 0.0

  human_audio_prob:
    local: 0.8
    neighbour: 0.2

  fire_visual_prob:
    local: 0.8
    neighbour: 0.0

  fire_thermal_prob:
    local: 0.8
    neighbour: 0.3

  failure_prob: 0.05

ugv2:
  type: rescuer
  capabilities: human_visual, human_audio
  human_visual_prob:
    local: 0.8
    neighbour: 0.0

  human_audio_prob:
    local: 0.8
    neighbour: 0.2

  failure_prob: 0.05